name: Main Validation

concurrency:
  group: ci-${{ github.event.number }}
  cancel-in-progress: true

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

  schedule:
    - cron: '31 1,12 * * *'

  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  linter:
    name: Linter
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/lint.yml

  markdownlint:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Markdownlint
    uses: nanlabs/devops-reference/.github/workflows/markdownlint.yml@main

  todo:
    if: github.event_name == 'push'
    name: TODO
    uses: nanlabs/devops-reference/.github/workflows/todo.yml@main

  pr-review:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Pull Request Validation
    uses: ./.github/workflows/pr-review.yml
