name: Main Validation

concurrency:
  group: main-check
  cancel-in-progress: true

on:
  push:
    branches:
      - main

jobs:
  linter:
    name: Linter
    uses: ./.github/workflows/lint.yml

  test:
    name: Test
    uses: ./.github/workflows/lint.yml

  markdownlint:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Markdownlint
    uses: nanlabs/devops-reference/.github/workflows/markdownlint.yml@main

  todo:
    if: github.event_name == 'push'
    name: TODO
    uses: nanlabs/devops-reference/.github/workflows/todo.yml@main

  pr-review:
    if: github.event_name == 'pull_request' && github.event.pull_request.draft == false
    name: Pull Request Validation
    uses: ./.github/workflows/pr-review.yml
